name: hmap CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: fish-shop/install-fish-shell@v2
      - name: Run Fishtape tests
        uses: fish-shop/run-fishtape-tests@v2
        with:
          patterns: tests/*.fish